# Generated by Django 4.2.29 on 2026-03-19 08:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(editable=False, max_length=20, unique=True)),
                ('property_location', models.CharField(max_length=300, verbose_name='Property / Site Location')),
                ('property_size', models.CharField(blank=True, max_length=100, verbose_name='Approximate Size (acres/ha/sqm)')),
                ('description', models.TextField(verbose_name='Project Description / Requirements')),
                ('urgency', models.CharField(choices=[('normal', 'Normal (2–4 weeks)'), ('urgent', 'Urgent (within 1 week)'), ('flexible', 'Flexible')], default='normal', max_length=30)),
                ('additional_notes', models.TextField(blank=True)),
                ('quoted_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('staff_notes', models.TextField(blank=True, verbose_name='Staff Review Notes')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('under_review', 'Under Review'), ('awaiting_client', 'Awaiting Client Response'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=30)),
                ('client_response_notes', models.TextField(blank=True)),
                ('client_responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_quotations', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to='services.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
